# Generated by Django 2.2.4 on 2020-07-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
