# Generated by Django 2.2.4 on 2020-07-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200706_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
