# Generated by Django 2.2.4 on 2020-07-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200711_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(related_name='exercises', to='app.Workout'),
        ),
    ]
