# Generated by Django 2.2.4 on 2020-07-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200711_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='workouts',
            field=models.ManyToManyField(related_name='days', to='app.Workout'),
        ),
    ]
