# Generated by Django 2.2.4 on 2020-07-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200707_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(),
        ),
    ]
