# Generated by Django 2.2.4 on 2020-07-11 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_week_workouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('workouts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='app.Workout')),
            ],
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
